### ISSUE TITLE
ModuleNotFoundError: No module named 'orb_slam3_ros.msg'

### ISSUE THREAD

**Issue by Kaixin181818** [YunxuanMao/ngel_slam#1]
您好！
在"ngel_slam/src/keyframeManager.py"下16行，from orb_slam3_ros.msg import BA_info，遇到‘ModuleNotFoundError: No module named 'orb_slam3_ros.msg'的问题，望回复
祝您阖家安康！

**Comment by YunxuanMao** [comment]
Hi! Sorry for the late reply. I've struggled with the git submodule. Here is the link to the two submodules I changed before: https://drive.google.com/drive/folders/1RvMYtInNbKuP8XBV2_Z4iEpCbDixKxLE?usp=drive_link. Feel free to download them and use them!
