### ISSUE TITLE
The links to the orb_slam3_ros and kaolin submodules do not exist.

### ISSUE THREAD

**Issue by yulgi** [YunxuanMao/ngel_slam#2]
Hi, 

Thanks for your excellent work. I would like to run the code and reproduce the experiment in the paper. But I find that the orb_slam3_ros and kaolin in the folder links to error URL links. And I get two empty folders when I git clone the repository. Could you please release the missing submodules 

Thanks a lot in advance!

**Comment by YunxuanMao** [comment]
Hi! Sorry for the late reply. I've struggled with the git submodule. Here is the link to the two submodules I changed before: https://drive.google.com/drive/folders/1RvMYtInNbKuP8XBV2_Z4iEpCbDixKxLE?usp=drive_link. Feel free to download them and use them!
