### ISSUE TITLE
No module named 'wisp.core'

### ISSUE THREAD

**Issue by YujiaLin-523** [YunxuanMao/ngel_slam#3]
There is something wrong with wisp and the output of the terminal is as follows:
```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from src.ngel_slam import NGEL_SLAM
  File "/home/ubuntu/lyj/Project/NGEL-SLAM/src/ngel_slam/src/ngel_slam.py", line 13, in <module>
    from src.models.renderer import Renderer
  File "/home/ubuntu/lyj/Project/NGEL-SLAM/src/ngel_slam/src/models/renderer.py", line 7, in <module>
    from wisp.core import Rays
ModuleNotFoundError: No module named 'wisp.core'
```
How can I tackle this problem? I am looking forward to your kind reply!

**Comment by YunxuanMao** [comment]
I think this is caused by different versions of kaolin wisp. You can use the kaolin wisp modified by me in the Google Drive link:  https://drive.google.com/drive/folders/1RvMYtInNbKuP8XBV2_Z4iEpCbDixKxLE?usp=drive_link.

**Comment by ShilangChen1011** [comment]
kaolin wisp can be not found in the link: https://drive.google.com/drive/folders/1RvMYtInNbKuP8XBV2_Z4iEpCbDixKxLE?usp=drive_link.
The provided link only contains the `orb-slam3-ros.zip` file.
![image](https://github.com/user-attachments/assets/fc399ec7-8af0-48c2-b7f9-3f7e5d0b0c05)
