### ISSUE TITLE
kaolin wisp can be not found in the link: https://drive.google.com/drive/folders/1RvMYtInNbKuP8XBV2_Z4iEpCbDixKxLE?usp=drive_link.

### ISSUE THREAD

**Issue by ShilangChen1011** [YunxuanMao/ngel_slam#4]
kaolin wisp can be not found in the link: https://drive.google.com/drive/folders/1RvMYtInNbKuP8XBV2_Z4iEpCbDixKxLE?usp=drive_link.
The provided link only contains the `orb-slam3-ros.zip` file.
![image](https://github.com/user-attachments/assets/fc399ec7-8af0-48c2-b7f9-3f7e5d0b0c05)

_Originally posted by @ShilangChen1011 in https://github.com/YunxuanMao/ngel_slam/issues/3#issuecomment-2292525308_

**Comment by YunxuanMao** [comment]
![Screenshot from 2024-08-16 15-22-49](https://github.com/user-attachments/assets/f6bb3550-7dd9-4892-877e-c29fcc888c50)
Thank you for your remind. I think something went wrong with my google drive. The kaolin folder was flagged for abused. I will try to upload the folder again.

**Comment by ShilangChen1011** [comment]
![image](https://github.com/user-attachments/assets/e0f619d7-91eb-4375-adb4-c987dbb2de47)
Sorry, I can't find the file. Can you send me by email(earcsirius@gmai.com)?

**Comment by YunxuanMao** [comment]
I have uploaded the submodules to baidu netdisk: 
Link: https://pan.baidu.com/s/1SUxY7pP_9de5kmw5G_7qYA 
Code: di2k. 
Feel free to use them.
