### ISSUE TITLE
Hoping author to confirm if the code can actually run

### ISSUE THREAD

**Issue by shibing15** [YunxuanMao/ngel_slam#6]
First and foremost, I greatly appreciate the author's work. However, I would like the runnability of the open-source code to be confirmed. I have personally fixed the following bugs, which, in my opinion, should not have been present in runnable code. Therefore, I kindly ask the author to verify the quality of the code.

1. src/keyframeManager.py line 88 ` self.self.new_volume_flag = ssnerf.shared_new_volume_flag` 
2. No keymanager defined in calss NGEL_SLAM

Even if I fix the above bugs, this code still cannot run successfully. So I hope the author can confirm the operability of the code. Thanks!

**Comment by YunxuanMao** [comment]
Sorry, I cannot confirm the code directly because the code I used in the paper is connected between two different computers (ORB-SLAM3 on my PC which does not have gpu and ngel on the server that cannot install ros) through socket server but the released code is a one-device version with ROS. The errors in the code are all about the connection between ORB and NGEL.  The only thing I can do is fix the bugs with your feedback.

**Comment by ShilangChen1011** [comment]
> First and foremost, I greatly appreciate the author's work. However, I would like the runnability of the open-source code to be confirmed. I have personally fixed the following bugs, which, in my opinion, should not have been present in runnable code. Therefore, I kindly ask the author to verify the quality of the code.
> 
> 1. src/keyframeManager.py line 88 ` self.self.new_volume_flag = ssnerf.shared_new_volume_flag`
> 2. No keymanager defined in calss NGEL_SLAM
> 
> Even if I fix the above bugs, this code still cannot run successfully. So I hope the author can confirm the operability of the code. Thanks!

Thank you for the author's work. I fully agree with @shibing15  viewpoint. I have also encountered similar issues and have resolved them. It seems to work well with the Replica dataset, but I still face many problems when using the TUM-RGBD dataset.

**Comment by ShilangChen1011** [comment]
> Sorry, I cannot confirm the code directly because the code I used in the paper is connected between two different computers (ORB-SLAM3 on my PC which does not have gpu and ngel on the server that cannot install ros) through socket server but the released code is a one-device version with ROS. The errors in the code are all about the connection between ORB and NGEL. The only thing I can do is fix the bugs with your feedback.

Thank you for your work and timely response. If you are running the project using two machines in collaboration, could you please share the code for the two-machine setup as well? It would be helpful if the installation and configuration documentation could be more detailed. We have similar requirements and conditions to run the project on two machines.

**Comment by shibing15** [comment]
> Sorry, I cannot confirm the code directly because the code I used in the paper is connected between two different computers (ORB-SLAM3 on my PC which does not have gpu and ngel on the server that cannot install ros) through socket server but the released code is a one-device version with ROS. The errors in the code are all about the connection between ORB and NGEL. The only thing I can do is fix the bugs with your feedback.

Thanks for your timely response. With your help, many bugs have been fixed. Currently, I have encountered the following problem in ngel_slam.py run(), which seems to be caused by the input of tracking() local_mapping() global_mapping() not being serializable.
![image](https://github.com/user-attachments/assets/9e45aec0-68c7-40a5-810d-60a2d91d1f02)

**Comment by YunxuanMao** [comment]
> > Sorry, I cannot confirm the code directly because the code I used in the paper is connected between two different computers (ORB-SLAM3 on my PC which does not have gpu and ngel on the server that cannot install ros) through socket server but the released code is a one-device version with ROS. The errors in the code are all about the connection between ORB and NGEL. The only thing I can do is fix the bugs with your feedback.
> 
> Thank you for your work and timely response. If you are running the project using two machines in collaboration, could you please share the code for the two-machine setup as well? It would be helpful if the installation and configuration documentation could be more detailed. We have similar requirements and conditions for running the project on two machines.

Hi! I release the 'NGEL with JSON frame infos' version code. You can simply save the keyframe information in a folder and then use them for mapping. This code enables you to reuse the keyframe information from ORB. Because I haven't run the code for about one year, if there are any problems, you are welcome to raise an issue.

**Comment by YunxuanMao** [comment]
> > Sorry, I cannot confirm the code directly because the code I used in the paper is connected between two different computers (ORB-SLAM3 on my PC which does not have gpu and ngel on the server that cannot install ros) through socket server but the released code is a one-device version with ROS. The errors in the code are all about the connection between ORB and NGEL. The only thing I can do is fix the bugs with your feedback.
> 
> Thanks for your timely response. With your help, many bugs have been fixed. Currently, I have encountered the following problem in ngel_slam.py run(), which seems to be caused by the input of tracking() local_mapping() global_mapping() not being serializable. ![image](https://private-user-images.githubusercontent.com/29483573/360371709-9e45aec0-68c7-40a5-810d-60a2d91d1f02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjE4MjQsIm5iZiI6MTcyNDMyMTUyNCwicGF0aCI6Ii8yOTQ4MzU3My8zNjAzNzE3MDktOWU0NWFlYzAtNjhjNy00MGE1LTgxMGQtNjBhMmQ5MWQxZjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwMTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMjlhZDU2YzM0ZDdmZDVmNmExM2NjMzkzMzNkODU2NzkzMWI2ZGIzNzk0NmQ0MWNhYjA1MDViNGI0YmU2NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k1IzuZgj4DDsj5fF01uAdohT9k-BnKlqfewT7qLBR-A)

Sorry, I don't know what caused the problem. I have never met the problem before. Check if you can use the new JSON version code I just released.

**Comment by shibing15** [comment]
> > > Sorry, I cannot confirm the code directly because the code I used in the paper is connected between two different computers (ORB-SLAM3 on my PC which does not have gpu and ngel on the server that cannot install ros) through socket server but the released code is a one-device version with ROS. The errors in the code are all about the connection between ORB and NGEL. The only thing I can do is fix the bugs with your feedback.
> > 
> > 
> > Thanks for your timely response. With your help, many bugs have been fixed. Currently, I have encountered the following problem in ngel_slam.py run(), which seems to be caused by the input of tracking() local_mapping() global_mapping() not being serializable. ![image](https://private-user-images.githubusercontent.com/29483573/360371709-9e45aec0-68c7-40a5-810d-60a2d91d1f02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjE4MjQsIm5iZiI6MTcyNDMyMTUyNCwicGF0aCI6Ii8yOTQ4MzU3My8zNjAzNzE3MDktOWU0NWFlYzAtNjhjNy00MGE1LTgxMGQtNjBhMmQ5MWQxZjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwMTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMjlhZDU2YzM0ZDdmZDVmNmExM2NjMzkzMzNkODU2NzkzMWI2ZGIzNzk0NmQ0MWNhYjA1MDViNGI0YmU2NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k1IzuZgj4DDsj5fF01uAdohT9k-BnKlqfewT7qLBR-A)
> 
> Sorry, I don't know what caused the problem. I have never met the problem before. Check if you can use the new JSON version code I just released.

Follow your advice. It works! But another problem arises, specifically about the modified kaolin library. module 'kaolin.ops.spc' has no attribute 'unbatched_make_parents'. Both the original kaolin and the modified kaolin's kaolin.ops.spc do not have the unbatched_make_parents attribute. So I think it is a problem with the uploaded kaolin library. Thanks!
![image](https://github.com/user-attachments/assets/5a717d67-b34f-4e68-9441-9c62fd0d3192)

**Comment by YunxuanMao** [comment]
> > > > Sorry, I cannot confirm the code directly because the code I used in the paper is connected between two different computers (ORB-SLAM3 on my PC which does not have gpu and ngel on the server that cannot install ros) through socket server but the released code is a one-device version with ROS. The errors in the code are all about the connection between ORB and NGEL. The only thing I can do is fix the bugs with your feedback.
> > > 
> > > 
> > > Thanks for your timely response. With your help, many bugs have been fixed. Currently, I have encountered the following problem in ngel_slam.py run(), which seems to be caused by the input of tracking() local_mapping() global_mapping() not being serializable. ![image](https://private-user-images.githubusercontent.com/29483573/360371709-9e45aec0-68c7-40a5-810d-60a2d91d1f02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjE4MjQsIm5iZiI6MTcyNDMyMTUyNCwicGF0aCI6Ii8yOTQ4MzU3My8zNjAzNzE3MDktOWU0NWFlYzAtNjhjNy00MGE1LTgxMGQtNjBhMmQ5MWQxZjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwMTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMjlhZDU2YzM0ZDdmZDVmNmExM2NjMzkzMzNkODU2NzkzMWI2ZGIzNzk0NmQ0MWNhYjA1MDViNGI0YmU2NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k1IzuZgj4DDsj5fF01uAdohT9k-BnKlqfewT7qLBR-A)
> > 
> > 
> > Sorry, I don't know what caused the problem. I have never met the problem before. Check if you can use the new JSON version code I just released.
> 
> Follow your advice. It works! But another problem arises, specifically about the modified kaolin library. module 'kaolin.ops.spc' has no attribute 'unbatched_make_parents'. Both the original kaolin and the modified kaolin's kaolin.ops.spc do not have the unbatched_make_parents attribute. So I think it is a problem with the uploaded kaolin library. Thanks! ![image](https://private-user-images.githubusercontent.com/29483573/360434325-5a717d67-b34f-4e68-9441-9c62fd0d3192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzgyMDAsIm5iZiI6MTcyNDM3NzkwMCwicGF0aCI6Ii8yOTQ4MzU3My8zNjA0MzQzMjUtNWE3MTdkNjctYjM0Zi00ZTY4LTk0NDEtOWM2MmZkMGQzMTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAxNTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNTM0YWNlN2E3ODc2YjFlNTEzZGNiYmQ1NGQxY2ViZjVkMzY5MDRlOGU3YjA1NTg1ZmIxOGI4MWNjZDBmN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mu0E3RRCgfa0psavPvJ72ojFyOJ40btCN09o6ChtuRw)

Hi! I have updated the kaolin library. Try it now.

**Comment by shibing15** [comment]
> > > > > Sorry, I cannot confirm the code directly because the code I used in the paper is connected between two different computers (ORB-SLAM3 on my PC which does not have gpu and ngel on the server that cannot install ros) through socket server but the released code is a one-device version with ROS. The errors in the code are all about the connection between ORB and NGEL. The only thing I can do is fix the bugs with your feedback.
> > > > 
> > > > 
> > > > Thanks for your timely response. With your help, many bugs have been fixed. Currently, I have encountered the following problem in ngel_slam.py run(), which seems to be caused by the input of tracking() local_mapping() global_mapping() not being serializable. ![image](https://private-user-images.githubusercontent.com/29483573/360371709-9e45aec0-68c7-40a5-810d-60a2d91d1f02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjE4MjQsIm5iZiI6MTcyNDMyMTUyNCwicGF0aCI6Ii8yOTQ4MzU3My8zNjAzNzE3MDktOWU0NWFlYzAtNjhjNy00MGE1LTgxMGQtNjBhMmQ5MWQxZjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwMTIwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMjlhZDU2YzM0ZDdmZDVmNmExM2NjMzkzMzNkODU2NzkzMWI2ZGIzNzk0NmQ0MWNhYjA1MDViNGI0YmU2NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k1IzuZgj4DDsj5fF01uAdohT9k-BnKlqfewT7qLBR-A)
> > > 
> > > 
> > > Sorry, I don't know what caused the problem. I have never met the problem before. Check if you can use the new JSON version code I just released.
> > 
> > 
> > Follow your advice. It works! But another problem arises, specifically about the modified kaolin library. module 'kaolin.ops.spc' has no attribute 'unbatched_make_parents'. Both the original kaolin and the modified kaolin's kaolin.ops.spc do not have the unbatched_make_parents attribute. So I think it is a problem with the uploaded kaolin library. Thanks! ![image](https://private-user-images.githubusercontent.com/29483573/360434325-5a717d67-b34f-4e68-9441-9c62fd0d3192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzNzgyMDAsIm5iZiI6MTcyNDM3NzkwMCwicGF0aCI6Ii8yOTQ4MzU3My8zNjA0MzQzMjUtNWE3MTdkNjctYjM0Zi00ZTY4LTk0NDEtOWM2MmZkMGQzMTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDAxNTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNTM0YWNlN2E3ODc2YjFlNTEzZGNiYmQ1NGQxY2ViZjVkMzY5MDRlOGU3YjA1NTg1ZmIxOGI4MWNjZDBmN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mu0E3RRCgfa0psavPvJ72ojFyOJ40btCN09o6ChtuRw)
> 
> Hi! I have updated the kaolin library. Try it now.

Thanks!
